FROM node:20-alpine


RUN apk update && apk add --no-cache openssl libc6-compat

WORKDIR /app


COPY package*.json ./
RUN npm install


COPY . .


RUN npx prisma generate

EXPOSE 5000


CMD ["sh", "-c", "npx prisma migrate deploy && npx prisma db seed && npm run start"]